# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabbr" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "1cfee4dbdd2a373f449249a50c1440cb592eb582d90a35711eb0f51214905070"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "752744ef070f2fae053c354515254ae30b8ca7859a866ddc99393fbfda6a9b3b"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1a68dcad9d1d38a92ac1943894985cdcca0856317d654f9e2494db2cc49dccd"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ba7af84afd43716b91fe0cce5900259f46aa74e9e193ef6f4181a07d1f7f4d2"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tabbr"
  desc "Fuzzy autocomplete for commands you actually use"
  homepage "https://github.com/waradu/tabbr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabbr"

  # No zap stanza required

  caveats <<~EOS
    To enable Tabbr in Zsh, add to ~/.zshrc:
      eval "$(tabbr init zsh)"

    For Bash 4.4 or newer, add to ~/.bashrc:
      eval "$(tabbr init bash)"

    For PowerShell 5.1 or newer with PSReadLine 2.0 or newer, add to $PROFILE:
      Invoke-Expression (& { (tabbr init pwsh | Out-String) })

    Restart your shell after installing or upgrading to load the shell integration.
  EOS
end
