# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabbr" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "e45c75a1a7c7ffdc8a4c0dcd89ebfd60962655af46e770bc78f25e6b408b1ec4"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a2856a9d524d8451cf5875b008e3697eac44c0c3014365e4892d627c128d95d"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9190efd3611c2bf67da4221e7e7236f2ba1e5e9acfea3a866635fc91ad177e66"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca78f78cd9da652f434ac4492fed3f0625a6f6f96c949e3b6b2535d16273adad"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tabbr"
  desc "Fuzzy autocomplete for commands you actually use"
  homepage "https://github.com/waradu/tabbr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabbr"

  # No zap stanza required

  caveats <<~EOS
    To enable Tabbr in Zsh, add to ~/.zshrc:
      eval "$(tabbr init zsh)"

    For Bash 4.4 or newer, add to ~/.bashrc:
      eval "$(tabbr init bash)"

    For PowerShell 5.1 or newer with PSReadLine 2.0 or newer, add to $PROFILE:
      Invoke-Expression (& { (tabbr init pwsh | Out-String) })

    Restart your shell after installing or upgrading to load the shell integration.
  EOS
end
