# This file was generated by GoReleaser. DO NOT EDIT.
cask "tabbr" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "8bec8bfb1ba852b1baffe739b5e46f4e652510a646102deb5204381ce98b55bd"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d3da809950f69a536813dd17dba075297fa25342e2721940fa7d14d7228069e"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c0869d369eb87a2a42774d53efe1cc740c432a40b9dc2cf3ef809e5b7657e7a9"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6aa2bc76a59777266fee7f92659e00d516d8e006e0091f40a3b5ae091ce4bd70"
      url "https://github.com/Waradu/tabbr/releases/download/v#{version}/tabbr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tabbr"
  desc "Fuzzy autocomplete for commands you actually use"
  homepage "https://github.com/waradu/tabbr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tabbr"

  # No zap stanza required

  caveats <<~EOS
    To enable Tabbr in Zsh, add to ~/.zshrc:
      eval "$(tabbr init zsh)"

    For Bash 4.4 or newer, add to ~/.bashrc:
      eval "$(tabbr init bash)"

    For PowerShell 5.1 or newer with PSReadLine 2.0 or newer, add to $PROFILE:
      Invoke-Expression (& { (tabbr init pwsh | Out-String) })

    Restart your shell after installing or upgrading to load the shell integration.
  EOS
end
